### ISSUE TITLE
Some charts are not loading

### ISSUE THREAD

**Issue by MTyson** [Devographics/Monorepo#110]
Some charts, like the back end frameworks, are showing errors instead of loading.

![image](https://user-images.githubusercontent.com/54382/189401429-c02f64fb-1f20-47b3-a458-d61193c1cbc6.png)

**Comment by ihinckle** [comment]
Bumped

**Comment by SachaG** [comment]
Oh sorry, I forgot to fix that. I'll have to rebuild the site.

**Comment by SachaG** [comment]
Fixed :)
