### ISSUE TITLE
[State of CSS] Remove explanatory code comments for :has() and :where()

### ISSUE THREAD

**Issue by zcorpan** [Devographics/Monorepo#123]
> :has() 2022
> CODE EXAMPLE
> ```
> /* Matching <a> elements that directly contain an <img> */
> a:has(> img)
> ```

Similarly for `:where()`

It seems to me the feature shouldn't be explained as people are more likely to select "Know what it is, but haven't used it" instead of "Never heard of it/Not sure what it is".

**Comment by SachaG** [comment]
That's a fair point, thanks.
