### ISSUE TITLE
[State of CSS] Missing "comment on any question" for some questions

### ISSUE THREAD

**Issue by zcorpan** [Devographics/Monorepo#124]
The introduction said that all questions would have the option to add additional comments. I noticed in the "CSS Usage" section that the comment button is not present. Maybe double-check all questions and add it where it should be available.

**Comment by zcorpan** [comment]
Maybe it's intentional since there are dedicated freeform questions in that section?

**Comment by SachaG** [comment]
Yes it's intentional, for now only features and libraries questions have the freeform comment button.
