### ISSUE TITLE
[State of CSS] Titles are slow to load or sometimes get stuck

### ISSUE THREAD

**Issue by zcorpan** [Devographics/Monorepo#125]
I noticed that some section titles start out showing something like "Css2022__something__something" and second or so later change to the proper title. The section title "Css2022__resources__podcasts_css__others" under "Resources" didn't change at all.

I see an error in the console, not sure if it's related:
```
2instrument.js:109 currentFocusIndex was not null, but currentTabindex was null during keypress
(anonymous) @ instrument.js:109
```

**Comment by SachaG** [comment]
Since then I've changed it to preload all titles at the start of a survey instead of on each page load, hopefully it'll make for a better experience.
