### ISSUE TITLE
No T-Shirt this year?

### ISSUE THREAD

**Issue by dwjohnston** [Devographics/Monorepo#140]
I look forward to the survey every year, mostly for the sick t-shirt. Is there no t-shirt this year? Or is the link hidden away?

**Comment by SachaG** [comment]
Which survey do you mean? https://2022.stateofgraphql.com/ didn't have a t-shirt, the CSS and JS surveys will probably feature the same t-shirt as last year since I'm not sure I'll have time to work with @chriskirknielsen to come up with a new design.

**Comment by SachaG** [comment]
Oh ok, the results for that survey are not out yet.
