### ISSUE TITLE
unable to load https://2021.stateofjs.com/en-US/libraries/front-end-frameworks

### ISSUE THREAD

**Issue by ericermerimen** [Devographics/Monorepo#142]
the chart is missing
![image](https://user-images.githubusercontent.com/86953900/197958078-a1b9aa2e-b2a6-4788-9755-bb1ba75fe7b5.png)

**Comment by kitswas** [comment]
Duplicate of #110 and #113.

**Comment by ericermerimen** [comment]
> Duplicate of #110 and #113.
sorry didn't notice about it, thanks
