### ISSUE TITLE
Issue with pt-PT/pt-BR locales

### ISSUE THREAD

**Issue by SachaG** [Devographics/Monorepo#144]
In `surveyform`, when switching locale to `pt-BR`, `getLocale()` sometimes incorrectly returns `pt-PT` instead. 

Also, `getLocale()` should probably return `locale` instead of `localeId` for consistency? Or else be renamed `getLocaleId()`?

```
  const { getLocale: getLocaleContext, setLocale } = useLocaleContext();
  const currentLocaleId = getLocaleContext();
```

**Comment by eric-burel** [comment]
I've changed a lot of this code in the incoming v13 update to simplify so it will stop being an issue (I hope). 
For current version, if the wrong locale is returned here, it's probably wrong in earlier step where the locale context is set?

**Comment by SachaG** [comment]
Yeah I'm not sure at what level the problem is coming in… I'll look into it monday.
