### ISSUE TITLE
"responses" field on "User" in GraphQL API hangs

### ISSUE THREAD

**Issue by SachaG** [Devographics/Monorepo#145]
In `user.server.ts`, it seems like this code hangs:

```
const responses = await ResponseConnector.find({
  userId: user._id,
});
```

For that reason the current user never loads in `SurveyAction.tsx`.

**Comment by SachaG** [comment]
It seems like the reason it hangs is that it's basically trying to do a `find({})` and fetch the entire collection. But no idea why…

**Comment by SachaG** [comment]
After updating to the latest `mongodb` package, things now work properly again. Yay!

**Comment by eric-burel** [comment]
I've added a line to double check if user._id is defined, just in case
