### ISSUE TITLE
You're amongst 100%?

### ISSUE THREAD

**Issue by RIP21** [Devographics/Monorepo#152]
Check the screenshot. It's definitely a bug :) 

![Screenshot_20221125-025441.png](https://user-images.githubusercontent.com/3940079/203885136-ff384a82-7c95-43ee-8612-5f356fdb8130.png)

**Comment by SachaG** [comment]
Math is hard… :(

**Comment by joeflateau** [comment]
It's a bug. my results screen flickered between 100% and 5% a few times. Though I would argue that producing a "knowledge score" is an issue in itself if the goal is to produce a comprehensive survey without skewing results

**Comment by jasonwilliams** [comment]
Just my 2 cents but you really shouldn’t do a “knowledge score” on a survey. This is not a quiz, the goal is to get honest answers to see what people are using and know. The results here will be skewed by people wanting a higher score.

**Comment by Vitruvius21** [comment]
> @SachaG Just my 2 cents but you really shouldn’t do a “knowledge score” on a survey. This is not a quiz, the goal is to get honest answers to see what people are using and know. The results here will be skewed by people wanting a higher score.

agree

**Comment by SachaG** [comment]
I think proving a "skew" would be nearly impossible because we don't have any "non-skewed" baseline to compare to. But assuming you're right, then we definitely **can't** stop doing the knowledge score, because that would then make any historical comparisons between "skewed" and "non-skewed" years invalid.

**Comment by eric-burel** [comment]
Closing as semi-solved (we have to manually trigger the quantile computation on each survey, will improve... some day)
