### ISSUE TITLE
Knowledge Score [OPINION]

### ISSUE THREAD

**Issue by scriptify** [Devographics/Monorepo#153]
I think the "Knowledge Score" Feature in the end could manipulate the result of future results. I get the motivation behind it to leave the person with a positive feeling about their "knowledge", but this gamification aspect could lead people in the future to unconsciously choose options which lead to a higher knowledge score.

Of course this is just a thesis, and I'm sure you had good reasons to include it.

Well done by the way, the new survey site is very cool!

**Comment by SachaG** [comment]
Interesting theory! But I think the only way to know if it's true or not is if we had some kind of baseline to compare it to, in other words a similar survey except without the gamification aspect. But since that probably won't happen I don't think we can decide either way…
