### ISSUE TITLE
Share on FB

### ISSUE THREAD

**Issue by dzienisz** [Devographics/Monorepo#159]
share on FB is blocked

**Comment by SachaG** [comment]
See my answer about LinkedIn issue… It would be great to fix that but honestly I wouldn't even know where to start.

**Comment by dzienisz** [comment]
Do you know what is Open Graph protocol?

It's HTML `<meta ... ` tags to help generate Social post information

I think we should first fix or add those.

**Comment by dzienisz** [comment]
I have send request to Facebook to unblock it.

**Comment by SachaG** [comment]
There's already a bunch of OG tags.

**Comment by SachaG** [comment]
> I have send request to Facebook to unblock it.

thanks!

**Comment by dzienisz** [comment]
Maybe we need to review them if they are correct?
