### ISSUE TITLE
read me links to 404

### ISSUE THREAD

**Issue by jaredatron** [Devographics/Monorepo#169]
The README.md in the root of this repo has this link: [Check all the features from our live app](https://vulcan-next.vercel.app/docs/features)  and it 404s as of this issue.

**Comment by SachaG** [comment]
I'll fix it thanks.

**Comment by eric-burel** [comment]
This is coming from vulcan next, whose docs are living here: https://vulcan-docs.vercel.app, I think the readmes are more up to date now
