### ISSUE TITLE
Knowledge Score Card Formatting Problems

### ISSUE THREAD

**Issue by douira** [Devographics/Monorepo#171]
Hi, thanks for designing this nice State of JS survey. I've left some feedback to the content of the survey in the field, but after the survey this knowledge score card has some small issues.

The list of "features that I might want to learn about" ends with `, .` which looks like a broken list join. Also, Hearing about 30/35 features meaning I'm above 100% of the participants seems awfully high, is that correct? (Maybe it's also just rounding, idk)

<img width="625" alt="Screenshot 2022-12-09 at 19 04 02" src="https://user-images.githubusercontent.com/17120022/206765348-32ed05b7-34e2-43c5-9916-8f42ccd3ae5c.png">

**Comment by eric-burel** [comment]
Thanks, I think the UI has evolved a lot since so it's fixed
![image](https://github.com/Devographics/Monorepo/assets/7983005/1fc41ec5-48c4-4c5d-968b-e21dfa044c62)
