### ISSUE TITLE
Sign Up / Subscription

### ISSUE THREAD

**Issue by AWCostabile** [Devographics/Monorepo#178]
So, this isn't so much a technical issue as it is a "publicity" / "awareness" issue?.. I've really been keen to participate in these surveys since seeing the 2018 "state of JS" survey. The issue is that I periodically check to see when the survey might be available but always seem to miss that brief window of opportunity to actually be a part of these...

I was hoping to get in touch with the SoJS team to figure out like, what is the usual timeline on the survey?.. Is it something like "Always the first 2 weeks of December"? I remember having done the survey in November I think and it was in some "beta" state where we could interact with it, but the answers wouldn't be taken at the end... Then I visited the site today only to find I was too late now...

I just wish there was something like a big label on the website to make it painfully obvious what sort of date(s) the survey is on - so we could know and put it in our calendars well in advance - or perhaps a mailing list we could sign up for to get an email for when the survey kicks off (if there is one, I couldn't figure out where to sign onto it 😮 !).

**Comment by SachaG** [comment]
You can sign up for the mailing list on https://stateofjs.com/en-us/ as well as on any results site. I don't think it's particularly hard to find. 

Doing the survey at fixed dates would be nice but it's not something I've managed to do so far sadly.

**Comment by AWCostabile** [comment]
Thanks =O! I see that the reason I was unable to find that page was because the below does not directly link to the page you provided:
https://survey.devographics.com/survey/state-of-js/2022
