### ISSUE TITLE
State of JS 2021 some sections not viewable 

### ISSUE THREAD

**Issue by eliasm307** [Devographics/Monorepo#179]
Some sections in the state of js 2021 are broken in terms of their titles and are also showing errors in the body where the data abd charts should be

**Comment by eliasm307** [comment]
E.g.

![Screenshot_20221219_103045_Chrome](https://user-images.githubusercontent.com/13420359/208416654-d030a04e-7c4a-4691-abe3-c7554231cad9.jpg)

**Comment by dagnelies** [comment]
I can confirm this, the site is broken for me too
