### ISSUE TITLE
Link to "State of GraphQL" survey appears twice in header

### ISSUE THREAD

**Issue by tadwohlrapp** [Devographics/Monorepo#180]
As the title states, the "State of GraphQL" survey is linked twice in the header of stateofjs.com and stateofcss.com. It also appears in the header of stateofgraphql.com and links to itself.

### On stateofjs.com:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/2788192/208861206-c4073fc4-2feb-4f4b-95ee-51bab3415814.png">

### On stateofcss.com:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/2788192/208861373-3abc7c50-2758-45da-ab61-c6be84dfe765.png">

### On stateofgraphql.com:
<img width="815" alt="image" src="https://user-images.githubusercontent.com/2788192/208862328-158c0e61-4e83-4a48-8fc3-b512665f7128.png">

**Comment by eric-burel** [comment]
Yes indeed, dup of #209, should be fixed soon
