### ISSUE TITLE
Unreadable data explorer text

### ISSUE THREAD

**Issue by hdodov** [Devographics/Monorepo#181]
The design of this section is not ideal. Under some circumstances, the content is unreadable:

![image](https://user-images.githubusercontent.com/5570098/209435800-5c62d821-f612-437e-8307-66e8940159d5.png)

You could perhaps put the percent value in the bottom right on top of some overlay, so that it's always visible.

**Comment by SachaG** [comment]
Thanks for the suggestion, I'll try that.

**Comment by SachaG** [comment]
I changed it as suggested.
