### ISSUE TITLE
Misleading CTA on "State of CSS 2022" on stateofcss.com

### ISSUE THREAD

**Issue by aremu-smog** [Devographics/Monorepo#184]
The **Most Recent** card which features **2022** has a CTA with the "Results Coming Soon" instead of "View Results" considering that the results are out
<img width="846" alt="image" src="https://user-images.githubusercontent.com/48217306/210873089-613fdb9b-9346-4416-a1cc-2b8814b237ba.png">

**Comment by SachaG** [comment]
Thanks, I fixed it :)
