### ISSUE TITLE
Some of the winner headers don't match the subtitle on State of JS 2022

### ISSUE THREAD

**Issue by Samathingamajig** [Devographics/Monorepo#185]
On https://2022.stateofjs.com/en-US/awards/, for the "Most Write-Ins" category, the header says the winner is "Astro", but the subtitle mentions "Elm" as winning; for "Most Adopted Feature", the header says "Top Level await()" but the subtitle says "nullish coalescing operator (??)". Every other category has the same winner as what's mentioned in the subtitle.

Based on the 2021 results, it looks like someone forgot to change these two subtitles.

<img width="821" alt="image" src="https://user-images.githubusercontent.com/29130894/211710264-8529154b-23d4-41e1-ae11-daa9e922cadf.png">

<img width="795" alt="image" src="https://user-images.githubusercontent.com/29130894/211709769-b73f3252-d8b5-4482-8b4b-f75dd715b26c.png">

**Comment by SachaG** [comment]
Oh you're right, I didn't notice that some descriptions were left over from previous years, thanks!
