### ISSUE TITLE
Avatar on the "Conclusion" page is squashed on mobile

### ISSUE THREAD

**Issue by pyotrr** [Devographics/Monorepo#190]
On the conslusion page there is a [CreditItem](https://github.com/Devographics/Monorepo/blob/dc3358422560893ca052628bd413b3ccfc362386/results/src/core/blocks/other/CreditItem.js#LL7C13-L7C13) component with an Avatar component. On mobile the avatar doesn't hold its aspect ratio

<img width="514" alt="image" src="https://user-images.githubusercontent.com/67952400/211812359-da4249be-71f3-40c5-87e0-320caf4f70eb.png">

This could be fixed by adding `min-height` and `min-width` to the avatar component or `flex: 1 1 0` to CreditItem's `Details` styled component if you's want something less invasive
https://github.com/Devographics/Monorepo/blob/dc3358422560893ca052628bd413b3ccfc362386/results/src/core/blocks/other/CreditItem.js#L42

**Comment by eric-burel** [comment]
Can't repro :/
