### ISSUE TITLE
Sveltekit is missing from the library tier list

### ISSUE THREAD

**Issue by tontonsb** [Devographics/Monorepo#191]
The tier list is supposed to include libraries used by 10% or more of the respondents. It seems that Sveltekit's usage is 11.9%.

**Comment by SachaG** [comment]
Libraries used by less than 10% of survey respondents are not included in this chart, which I'm guessing is probably SvelteKit's case?

**Comment by tontonsb** [comment]
@SachaG isn't "used by" the same as the "usage" that's shown in the data?

SvelteKit has 11.9% "usage" and it seems that "would use again" alone was around 11% (92.5% of 11.9%).
