### ISSUE TITLE
Data explorer bug

### ISSUE THREAD

**Issue by jkjustjoshing** [Devographics/Monorepo#192]
At this URL https://2022.stateofjs.com/en-US/explorer/?xField=disability_status&yField=yearly_salary&xSection=demographics&ySection=demographics&unit=percentage&respondentsPerDot=10&percentsPerDot=1&dotsPerLine=10&showCellCounts=true

I see this
<img width="1176" alt="image" src="https://user-images.githubusercontent.com/813192/211830465-85c06fd4-0b8c-4ead-9d9a-25608594c6d9.png">

**Comment by SachaG** [comment]
Fixing now.
