### ISSUE TITLE
Data explorer percent text gap

### ISSUE THREAD

**Issue by exportio** [Devographics/Monorepo#193]
There is no gap between the huge % symbol and the value to the right of it.  Attached is an image after I changed the gap from 2px to 6px on the .eNMfME class.

![image](https://user-images.githubusercontent.com/898232/211845080-46b5aa5b-0aad-471b-8d02-5c3779fe165b.png)

**Comment by SachaG** [comment]
Good catch, that icon wasn't supposed to be this big. I'll fix it.
