### ISSUE TITLE
Why have backend frameworks been moved to the 'other tools' section?

### ISSUE THREAD

**Issue by yannxaver** [Devographics/Monorepo#197]
It doesn't show user satisfaction anymore unlike last year when they still had a dedicated section. This seems contrary to the growing trend of JavaScript full stack development.

**Comment by SachaG** [comment]
The previous years' back-end section also mixed in Astro, Next.js, etc. and I wanted to give those their own category since there is a lot of movement in that space. I hope to eventually create a separate, dedicated survey for back-end frameworks more specifically.
