### ISSUE TITLE
Demography has less countries.

### ISSUE THREAD

**Issue by fResult** [Devographics/Monorepo#201]
it should display every countries which answer the stateofjs2022

**Comment by SachaG** [comment]
That's a big list though, I have to think about how to best present it if we really want to display every single country…

**Comment by fResult** [comment]
In stateofjs2021 has very many countries to show.
https://2021.stateofjs.com/en-US/demographics

In my opinion, it would be nice if we can see every countries.

Becoz we can cheer up ppl in my country to do survey more with "the number"
each year.
We can say them, "Hey, this year we have ppl did this survey more than the
last year. Next year I hope seeing more than this"

**Comment by eric-burel** [comment]
Might be solved by the introduction of a Data explorer that would be more self-service
But countries with few respondent cause privacy issues see #330

**Comment by fResult** [comment]
Thanks for considering and improving this feature.  
Cheers. 😄
