### ISSUE TITLE
Closure compiler interest

### ISSUE THREAD

**Issue by jespertheend** [Devographics/Monorepo#202]
I'm writing a library and was wondering whether I would need to support closure compiler. So I decided to check stateofjs to see whether closure compiler is still something that lots of people use or if it is now a relic of the past. But to my surprise closure compiler wasn't listed. Was this ever considered, or is its usage so low that it doesn't deserve to be in the list?

**Comment by SachaG** [comment]
If it's not listed in the "other responses" tabs in the "other tools" section then yes it means it wasn't mentioned by respondents, or else that the mentions were quite low (lower than ~10 mentions overall).

**Comment by jespertheend** [comment]
Alright seems like it wasn't mentioned much then. Thanks for the info!
