### ISSUE TITLE
Comparison feature broken on many charts

### ISSUE THREAD

**Issue by sylwiavargas** [Devographics/Monorepo#207]
I'm interested in looking at the blogs/podcasts/people through the perspective of gender, ethnicity, and years of experience. However, the comparison feature seems broken in most charts, not only in this section. 

## Reproduction steps

To reproduce:
1. Go to https://2022.stateofjs.com/en-US/resources/#people_others
2. Select "Compare data" button on the right
3. Select "gender" (for example)
4. Wait for the data to be processed

## Screenshots 

<img width="1134" alt="People chart with an error: 't.map is not a function' and the word 'debug' printed on the page." src="https://user-images.githubusercontent.com/45401242/215475596-064ed3cf-ee16-4514-9710-70cd27a00f06.png">
<img width="1134" alt="Video creators chart with an error: 't.map is not a function' and the word 'debug' printed on the page." src="https://user-images.githubusercontent.com/45401242/215475602-2fcdd286-a1b4-4867-97f0-861217ac9682.png">

**Comment by SachaG** [comment]
I think it should be fixed?

**Comment by sylwiavargas** [comment]
Thank you, it is!
