### ISSUE TITLE
Header links on State of JS and State of CSS link to State of GraphQL multiple times

### ISSUE THREAD

**Issue by eScribMac** [Devographics/Monorepo#209]
<img width="743" alt="image" src="https://user-images.githubusercontent.com/4968747/218892395-e4af3215-f840-41b4-a916-ca254fadf88c.png">
<img width="815" alt="image" src="https://user-images.githubusercontent.com/4968747/218892415-a31e8707-b637-4826-8a13-1d34b50d0350.png">

**Comment by eric-burel** [comment]
My bad, this is because I've introduced a demonstration survey that is meant to stay always open based on the "State of GraphQL". Should be fixed in next release.
