### ISSUE TITLE
State of CSS 2022 doesn't render charts

### ISSUE THREAD

**Issue by shekeg** [Devographics/Monorepo#211]
Hi! Thanks for the State of CSS and the State of JS. I really appreciate it.

I'm trying to open any page with a chart (https://2022.stateofcss.com/en-us/features/), but charts are not rendered and I see errors in the dev tools console. 

I use Chrome Version 109.0.5414.122 (Official Build) (64-bit)

Errors from dev tools console:

```
Refused to execute script from 'https://2022.stateofcss.com/app-8e257789f8c772135ad2.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
2022.stateofcss.com/:1 
        
Refused to execute script from 'https://2022.stateofcss.com/webpack-runtime-ecf9e10fadb81a54cd13.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
2022.stateofcss.com/:1 
        
Refused to execute script from 'https://2022.stateofcss.com/framework-f5d4ebb958eff2ae75b5.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled.
```

**Comment by eric-burel** [comment]
Hmm weird because I see "application/javascript" for "app-XXX.js" file in the network tab.
If you happen to be able to reproduce, can you maybe check the network? This may happen if there is an error upstream and the server returns an empty file for instance, but this sounds like a transient issue.

**Comment by shekeg** [comment]
> Hmm weird because I see "application/javascript" for "app-XXX.js" file in the network tab, using Chromium. If you happen to be able to reproduce, can you maybe check the network? This may happen if there is an error upstream and the server returns an empty file for instance, but this sounds like a transient issue.

For now, it works well. I can't reproduce it, closing the issue
