### ISSUE TITLE
Access survey edition in top level nav

### ISSUE THREAD

**Issue by eric-burel** [Devographics/Monorepo#223]
Problem: Nav is in an upper layout, so we may not have an edition depending on the context

"Layouts do not have access to the current route segment(s). To access route segments, you can use [useSelectedLayoutSegment](https://nextjs.org/docs/app/building-your-application/routing/docs/app/api-reference/functions/use-selected-layout-segment) or [useSelectedLayoutSegments](https://nextjs.org/docs/app/api-reference/functions/use-selected-layout-segments) in a Client Component."

Of course, `useSelectedLayoutSegments` points to nothing :) But the idea is:
- in Nav, check if there are route parameter matching an edition
- If yes, render "EditionNav" that get the edition from client context using "useEdition"
- If no render "GenericNav" that do not call "useEdition"

**Comment by SachaG** [comment]
Probably best to: 

- Put nav in edition level layout
- Find a way to opt out of top level layout so we don't end up with two navs

**Comment by eric-burel** [comment]
https://nextjs.org/docs/app/building-your-application/routing/route-groups
