### ISSUE TITLE
Get rid of passport (maybe)

### ISSUE THREAD

**Issue by eric-burel** [Devographics/Monorepo#232]
Upgrading next-connect doesn't work, as it doesn't document Express + route handlers

See https://github.com/hoangvvo/next-connect/issues/228

Let's rewrite the auth part to avoid depdnency on Passport, which brings not much additional value.

Then, we will be able to update to Sentry Next 7, see https://github.com/getsentry/sentry-javascript/issues/8328

**Comment by eric-burel** [comment]
@SachaG seems like NextAuth is solid enough for us, given that it's optimized for Next and supported by Vercel: https://next-auth.js.org/

We would need to add Anonymous auth strategy, and I don't know if it supports pin code out of the box

**Comment by SachaG** [comment]
PIN code is a nice-to-have so we don't really need to worry about it, but we'd need the magic links yeah… I'm fine to wait until next year to make any new changes to `surveyform` btw.

**Comment by eric-burel** [comment]
Closing as : won't touch what works perfectly well
We can live forever happily with an API route around
