### ISSUE TITLE
Sharing on twitter after the survey results in undefined url

### ISSUE THREAD

**Issue by LukyVj** [Devographics/Monorepo#233]
Here's what I see when I click on the twitter icon once I was finished with the survey: 

<img width="873" alt="Screenshot 2023-06-20 at 11 58 21" src="https://github.com/Devographics/Monorepo/assets/1630200/db77c30f-0183-4e08-a7ed-ca7e0f75e698">
<img width="704" alt="Screenshot 2023-06-20 at 11 58 25" src="https://github.com/Devographics/Monorepo/assets/1630200/3e6eba74-aac7-4487-ae6e-e3971baeee3e">

**Comment by SachaG** [comment]
Thanks, fixing it :)

**Comment by LukyVj** [comment]
Stellar! Thanks 🙏 

Really nice survey this year! Lotta good stuff! 

Well done, really eager to see these results
