### ISSUE TITLE
State of CSS: How to view bookmarked features after survey close?

### ISSUE THREAD

**Issue by Dahmon** [Devographics/Monorepo#249]
Hello! While completing the survey this year we were able to save/bookmark features that were mentioned.
I recall visiting the site a couple days after I completed the survey and I was still able to see this list, however, I logged into the site this afternoon to look into these marked topics further and I am unable to find any remnant of the list.

Was this removed, only available while the survey was running, or something else?
Of course I can look through the questions to find these features again, but that's not ideal.
I would have written the topics down on a piece of paper had I not been given the option to save them during the survey.

Anyway, no harm done either way, I'm just a bit confused.

**Comment by funbunch** [comment]
Having the same issue and really wanted to be able to view the reading list I had saved.

**Comment by SachaG** [comment]
Sorry about that, let me look into it.

**Comment by SachaG** [comment]
Can you check now?

**Comment by funbunch** [comment]
Yes, it works and I can see it now. Thanks!
