### ISSUE TITLE
Easier way to reach latest survey

### ISSUE THREAD

**Issue by fgarcia** [Devographics/Monorepo#250]
I find kind of cumbersome reaching for the latest survey. 

I know I have to type the current year in `http://{year}.stateofjs.com` and if the domain is not found, try a previous year. Is there a reason for not having a link to the latest at `http://stateofjs.com` or a redirect from `http://latest.stateofjs.com`?

**Comment by SachaG** [comment]
I could be wrong, but I think the original issue was posted at a time where the homepages were broken and didn't feature links to the surveys.

**Comment by fgarcia** [comment]
@SachaG you are right, I've just visited the page and clearly there was no link to the latest survey before
