### ISSUE TITLE
Easier access to reading lists + tests

### ISSUE THREAD

**Issue by eric-burel** [Devographics/Monorepo#255]
Related to https://github.com/Devographics/Monorepo/issues/249
Right now we have to go to "see my response" and "finish survey", we could easily add a standalone "/readling-list" page in addition to those + a link to it alongside the "see my response again" button

**Comment by SachaG** [comment]
Good idea!

**Comment by funbunch** [comment]
Now that I closed the tab I can no longer access the reading list again. The Finish survey part only takes me to the share screen. So whatever can help!

**Comment by SachaG** [comment]
Oh sorry, fixing it now.
