### ISSUE TITLE
"Stay Tuned" section - entering email and clicking "Notify Me" does not work

### ISSUE THREAD

**Issue by theadin** [Devographics/Monorepo#276]
On this page https://2023.stateofcss.com/en-US trying to add my email does nothing.

Using Developer tools I can see the following error:

`Access to fetch at 'https://emailoctopus.com/lists/undefined/members/embedded/1.3/add' from origin 'https://2023.stateofcss.com' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.`

`POST https://emailoctopus.com/lists/undefined/members/embedded/1.3/add net::ERR_FAILED 404`

**Comment by eric-burel** [comment]
Ping @SachaG , I guess the new domain 2023 is not taken into account but I also see an "undefined" in the fetched URL

**Comment by SachaG** [comment]
I see the issue, we weren't querying for the listId in our GraphQL query. Fixing it now.
