### ISSUE TITLE
StateOfCSS: No available data for block css_frameworks_experience_linechart | path(s):

### ISSUE THREAD

**Issue by LordSimal** [Devographics/Monorepo#282]
Currently https://2023.stateofcss.com/en-US/css-frameworks/ is broken
![image](https://github.com/Devographics/Monorepo/assets/9105243/07257e7c-e864-4bb2-aa41-95fd7ad3265f)

```
No available data for block css_frameworks_experience_linechart | path(s): dataAPI.surveys.state_of_css.css2023.css_frameworks.css_frameworks_experience_linechart | type: ToolsRatiosLineChartBlock
```

I have no JS errors in the browser console or failed network requests

**Comment by aaronmeder** [comment]
Same for me...everything after "overscroll-behaviour" has no data.
Tried new browser / Incognito Session. 

![Screenshot 2023-09-06 at 08 39 50](https://github.com/Devographics/Monorepo/assets/5564163/bb502e30-7adb-4466-a296-1d9d47672d4f)

**Comment by LordSimal** [comment]
Seems they fixed it.
