### ISSUE TITLE
Dead images on demo survey page

### ISSUE THREAD

**Issue by okplanbo** [Devographics/Monorepo#288]
page: https://survey.devographics.com/en-US/survey/demo-survey/2022

404 link: https://assets.devographics.com/surveys/demo2022.png

![image](https://github.com/Devographics/Monorepo/assets/26038255/1742510d-3e33-4277-a084-d6bb08957fff)

also at the bottom:

![image](https://github.com/Devographics/Monorepo/assets/26038255/e6e69d16-fc96-45b4-92c4-f65bf4692086)

**Comment by SachaG** [comment]
Thanks! I think that image just doesn't exist. This is more of an internal test survey for us.

**Comment by eric-burel** [comment]
Thanks @okplanbo that's indeed our test survey, it is improved progressively as we work on our testing infrastructure and not really used as a "commercial" demo yet
