### ISSUE TITLE
state-of-html - i18n missing key - `user_info.other_surveys.question`

### ISSUE THREAD

**Issue by flexbox** [Devographics/Monorepo#300]
there is a missing key for `user_info.other_surveys.question`

**How to reproduce?**
1. Surveys / State of HTML 2023
2. About you

![cleanshot-Firefox-DsmlL9LZ](https://github.com/Devographics/Monorepo/assets/360936/db95ae9d-84bb-49e0-af0c-ed131ec0aab7)

**Comment by SachaG** [comment]
Thanks, fixed it :)
