### ISSUE TITLE
Feature request - faster onboarding for gmail users

### ISSUE THREAD

**Issue by flexbox** [Devographics/Monorepo#301]
**Scenario**
I wanted to sign in to the HTML 2023 survey, but the magic link email landed in my spam.
<img width="851" alt="image" src="https://github.com/Devographics/Monorepo/assets/360936/32295f2d-1e53-46f7-a1e6-bdb2143d70c5">

I think we could spark joy for gmails users (not sure if it's available for other email providers)

**Story**
As a Gmail user
I can click on a link and open my inbox filtered
So that I can sign in faster

The link is this one
```
https://mail.google.com/mail/u/0/#search/from%3A%40stateofhtml+in%3Aanywhere
```

Example:
<img width="677" alt="image" src="https://github.com/Devographics/Monorepo/assets/360936/61580ca5-5645-43ba-b39e-2ea732b64040">

<img width="1193" alt="image" src="https://github.com/Devographics/Monorepo/assets/360936/dab4c51e-cd86-4d49-a04f-9093d54f4380">

**Comment by SachaG** [comment]
Good idea! Should be easy to do :)

**Comment by eric-burel** [comment]
Done, @SachaG I am currently getting the email domain based on surveyId, but that's maybe something we have in the survey config? So "state_of_html" becomes "stateofhtml" (I lowercase too)
But there might be edge cases when doing this way eg tokyodev?

**Comment by SachaG** [comment]
The email domain should be `mail.${survey.domain}`, for example `mail.stateofhtml.com`.
