### ISSUE TITLE
Range selection comment component does not detect when a response has been selected

### ISSUE THREAD

**Issue by rotan-hanrahan** [Devographics/Monorepo#311]
In the "how do you divide your time..." question we are presented with a scale (100% HTML on left, 100% JS on the right). If you find that you want to comment on this scale before actually selecting one of the 9 possible options you can click the comment box, and the box will say "You didn't pick any response. Tell us why:"

However, if you then go back and pick one of the 9 options, the comment stays there falsely accusing you of not picking any response.

![false-accusation](https://github.com/Devographics/Monorepo/assets/24960145/fcded127-4cfe-4ed1-9e3e-fc4e2950b5e0)

**Comment by eric-burel** [comment]
Might be kinda related to https://github.com/Devographics/Monorepo/issues/290

**Comment by eric-burel** [comment]
Will be fixed in next release, thanks for catching this out. Numbers are not considered truthy by lodash "isEmpty" somehow so we needed an additional check.
