### ISSUE TITLE
The StateOfHTML twitter share link has uncompiled template strings

### ISSUE THREAD

**Issue by prakashchokalingam** [Devographics/Monorepo#316]
Content:

I got a 635 pts knowledge score on this year’s #StateOfHTML survey! I have used **{usage_count}** features, and knew **{awareness_count}** more. Can you beat my score? https://survey.devographics.com/survey/state-of-html/2023?source=post_survey_share 

The usage_count and awareness_count are not parsed with actual value.

<img width="511" alt="Screenshot 2023-09-27 at 12 54 14 PM" src="https://github.com/Devographics/Monorepo/assets/5512765/28d8b346-3b9f-4040-8b92-f9d2967118d6">

**Comment by eric-burel** [comment]
Fixed in next release thank you!
