### ISSUE TITLE
Stuck on loading spinner after following login link (Safari, iOS)

### ISSUE THREAD

**Issue by chrismear** [Devographics/Monorepo#317]
URL: https://survey.devographics.com/en-US/account/magic-login?editionId=html2023&token=[REDACTED]&surveyId=state_of_html

![image](https://github.com/Devographics/Monorepo/assets/6186/8d7ee926-cba9-4c34-8baa-29fb79001d87)

**Comment by SachaG** [comment]
What happens if you reload the page? Did you find a way to make it work in the end?

**Comment by chrismear** [comment]
Same result when I reloaded the page. In the end, I completed the survey anonymously.

**Comment by eric-burel** [comment]
Can't repro on my iPad, probably  a transient issue
I've noticed the app doesn't run on older iPads, I'll try to add some polyfills for iOS
