### ISSUE TITLE
GDPR-friendly and agnostic conversion tracking

### ISSUE THREAD

**Issue by eric-burel** [Devographics/Monorepo#321]
Goal:
- get number of visits
- get an approximation of unique visitors

Constraints:
- avoid personal data so no IP
- avoid JS cookies (see Safari ITP https://www.apple.com/safari/docs/Safari_White_Paper_Nov_2019.pdf) so favour HTTP-only cookies
- assign a token to new visitors if they don't have one (can be done in middleware I think, though setting cookies used to have some bugs in earlier versions)
- associate token and userId upon connexion, in particular for magic login with email

Tech choices:
- **there might be existing solutions for Next we don't need to reinvent the wheel**
- store data on Mongo? Is it ok to have a lot of queries? Redis is better suited for fast computation but it doesn't preserve values, so we have to regularly store new data anyway. Perhaps useful for optimization
- we'll need a few queries to compute the counts from raw events
- + UI in surveyadmin

@SachaG

**Comment by eric-burel** [comment]
Plausible could be self-hosted: https://plausible.io/data-policy
It seems to use a hashed IP address with rotating salt, which could be ok in our use case (as long as the IP can't be retrieved later on)

**Comment by SachaG** [comment]
I'm already paying for the non-self-hosted Plausible so we could always just use that if we don't want to build our own internal tracking system.

**Comment by eric-burel** [comment]
I've read the Plausible doc and it's 100% what we need
Vercel is not bad either, and included anyway so we can't stick to it for non self-hosted surveys
