### ISSUE TITLE
Your email service is broken.

### ISSUE THREAD

**Issue by varna** [Devographics/Monorepo#322]
Your email services don't work this year.

1. When I got the first email for State of HTML, the links were blocked by my browser because of "security" issues.
2. Today I tried to take the survey again, but I don't get the magic link to login. I tried waiting, resending, checking spam and trash boxes, nothing.

I'm using gmail on Mail app (macOS). I can only guess that Google is being pain in the ass again, and started blocking your mail server.

**Comment by TruJared** [comment]
Here's the specific error I pulled from the network panel 
```{
    "success": false,
    "error": {
        "code": "EMESSAGE",
        "response": "554 Message rejected: Email address is not verified. The following identities failed the check in region US-EAST-1: surveys@devographics.com",
        "responseCode": 554,
        "command": "DATA"
    }
}

**Comment by SachaG** [comment]
Sorry, I changed the email we're sending from by mistake. Changing it back should fix it.

**Comment by eric-burel** [comment]
Will close for now
