### ISSUE TITLE
Firefox unresponsive after editing a text field

### ISSUE THREAD

**Issue by openmindculture** [Devographics/Monorepo#343]
The following issue happened once, about halfway in the middle of the State of JavaScript survey when I clicked and focused a text field that I had filled before and pressed the backspace key several times to edit a typo.

I could not reproduce the issue later when I started in another survey session in Firefox and another one in Vivaldi.

Browser error message: 
![Screenshot](https://github.com/Devographics/Monorepo/assets/6377941/b79972d1-da77-42d8-b839-1ad355004045)
Screenshot: “State of JavaScript 2023: Build Tools — Mozilla Firefox” is not responding.
You may choose to wait a short while for it to continue or force the application to quit entirely. Wait / Force Quit

Full page screenshot:
![built tools page screenshot with error message](https://github.com/Devographics/Monorepo/assets/6377941/e4e9941b-c452-49b0-b83f-82e0174a04ec)

The error occurred on the "Build Tools" page when trying to edit the first issues text field.
https://survey.devographics.com/en-US/survey/state-of-js/2023/{__SESSION_ID__}/6

After I forced quit and restarted Firefox, I could resume the survey. No more problems.
I have no more details as I did not have developer tools open, and there was no core dump log as I chose to quit the browser "deliberately", but here are my browser and OS version:

Firefox Browser 120.0 (64-bit) Mozilla Firefox Snap for Ubuntu canonical-002 - 1.0
Ubuntu 22.04.3 LTS Linux 6.5.0-10008-tuxedo # 8 x86_64 GNU/Linux

**Comment by eric-burel** [comment]
Thanks, this component is new and gave me a hard time (forms are terrible in React...), there might be an edge case where an infinite loop could happen. I'll try to repro.

**Comment by eric-burel** [comment]
Closing for now, this component was buggy back then
