### ISSUE TITLE
Error when I add more than 9 items to a list

### ISSUE THREAD

**Issue by remnantkevin** [Devographics/Monorepo#347]
- Browser: Firefox 120.0 (64-bit)
- OS: macOS 13.5.2

In the State of JS 2023 survey, in the Resources step, if I add more than 9 items to any of the lists, for example for podcasts, then I get the following error on the web page:

```
Could not load question podcasts (m[0] is undefined)
```

In the console the error is:

```
TypeError: m[0] is undefined
    tx TextList.tsx:343
```

If I click on the file name, I am taken to this part of the file:

```ts
  const selectFirstVirtualItem = useCallback(
    () => selectItem(wrapperRef.current, virtualItems[0].key),
    [virtualItems[0].key] // line 343
  );
```

**Comment by eric-burel** [comment]
Thanks @remnantkevin for figuring this out!
@SachaG now the limit is actually enforced without bugs so we might want to display it, though I think users intuitively get that after ten they stop having new inputs so they reached a limit
