### ISSUE TITLE
Some unparsed l10n texts in State of HTML 2023

### ISSUE THREAD

**Issue by saschanaz** [Devographics/Monorepo#361]
![A comments popup that shows raw l10n codes for comments.filter.all and options.sentiment.used.positive.label.short](https://github.com/Devographics/Monorepo/assets/3396686/5ebef247-f90c-4011-9377-af60478b8032)

The comments popup has some raw machine-readable texts in it 👀

**Comment by eric-burel** [comment]
Seems fixed
Falling back to i18n key allows us to make the items at least slightly interpretable, though we strive to avoid this
It usually happens when the cache is triggered, so the update of i18n files is delayed
