### ISSUE TITLE
link to section for "other tools" broken

### ISSUE THREAD

**Issue by srenatus** [Devographics/Monorepo#381]
Clicking any of the 🔗 in the sections of [Other tools](https://2023.stateofjs.com/en-US/other-tools/), like "Javascript Runtimes" 
1. sends me to https://share.stateofjs.com/share/prerendered?localeId=en-US&surveyId=state_of_js&editionId=js2023&blockId=runtimes&params=&sectionId=other_tools
2. which forwards to https://2023.stateofjs.com/en-US/other_tools/#runtimes. 

That is a 404, because it should be `other-tools`, not `other_tools`.

**Comment by SachaG** [comment]
Same issues as https://github.com/Devographics/Monorepo/issues/380
