### ISSUE TITLE
Chart rendering completely broken in Safari 15.6

### ISSUE THREAD

**Issue by blaumeise20** [Devographics/Monorepo#382]
I'm still on an older Safari version for various reasons, and it seems that the charts are completely broken in this version:
![Bildschirmfoto 2024-06-21 um 09 46 37](https://github.com/Devographics/Monorepo/assets/62756994/474f9957-491c-4977-996a-d0b2e568f9ef)

**Comment by blaumeise20** [comment]
![Bildschirmfoto 2024-06-21 um 09 55 28](https://github.com/Devographics/Monorepo/assets/62756994/49f75922-5229-4413-a072-57488782d448)
Some sites break even more...

**Comment by SachaG** [comment]
Yes, the site does require support for a couple newer features: 

https://caniuse.com/css-subgrid
https://caniuse.com/mdn-javascript_builtins_array_toreversed
