### ISSUE TITLE
Missing display picture and homepage url in {State of js > resources > video creators}

### ISSUE THREAD

**Issue by ardentkilnfire** [Devographics/Monorepo#383]
The display picture and the homepage are missing for joy of code and some other creators.
Joy of code homepage: https://joyofcode.xyz
joy of code display picture: https://imgur.com/a/JiPHU4r

**Comment by SachaG** [comment]
Currently only individual people and a few libraries have avatars. Adding icons or logos for every single item mentioned in the survey would be a huge added workload so I'm not considering it right now, although if the community pitched in I suppose it could be doable in the future.
