### ISSUE TITLE
Weird "arisa_fukuazki" debug block?

### ISSUE THREAD

**Issue by sparecycles** [Devographics/Monorepo#393]
<img width="672" alt="image" src="https://github.com/Devographics/Monorepo/assets/719818/b17ade9a-5cbf-4608-98f1-c1f221b030ee">

```
No available data for block arisa_fukuzaki | path(s): dataAPI.entity_arisa_fukuzaki | type: PicksBlock
```

Found on https://2023.stateofjs.com/en-US/features/#async_features

Specifically between "Browser APIs Pain Points" and "Reading List"

**Comment by alinkedd** [comment]
It should be fixed by now.

However, in case translations are absent, it falls back to keys instead of English text.
![Screenshot from 2024-06-29 03-06-17](https://github.com/Devographics/Monorepo/assets/9061686/5993b274-14a2-4b26-8f2b-95e3108e02a6)
