### ISSUE TITLE
Vercel top 3 for Hosting Services? Axios ranked 17th? What gives?

### ISSUE THREAD

**Issue by Rivera-Emmanuel** [Devographics/Monorepo#399]
I didn’t know where else to report what appear to be data anomalies to me.

For the 2023 State of JS Survey:

1. The respondent population looks heavily skewed towards Vercel for the “Other Tools/Hosting Services” section and ranked as number 2. 

2. Additionally, Axios being ranked 17th in “Other Tools/Libraries” is inconceivable.

3. Nearly one-third (~5k) of the population is from an unknown (“Over Limit”) country. What does this mean, and are the respondents of this unknown country contributing to items 1 and 2?

Items 1 and 2 simply don’t appear to be representative of what most people in this industry would consider reasonably accurate, or within the expected response set from a population that exists within the normal distribution curve.

**Comment by SachaG** [comment]
What data are you basing your conclusions on?

As for the "over limit", the chart is limited to the top 20 countries so the other ones are all grouped under that bucket. That doesn't mean the country isn't known, it's just not shown.

**Comment by Rivera-Emmanuel** [comment]
I do not have any objective evidence to present. The burden of proof is not on me.

If Vercel is number 2 cloud hosting technology in the world amongst JS/TS developers or respondents of the survey, then those are the facts.

**Comment by SachaG** [comment]
> If Vercel is number 2 cloud hosting technology in the world amongst JS/TS developers or respondents of the survey, then those are the facts.

Yes, it would seem like they are.
