### ISSUE TITLE
[results/js2023] "UNDEFINED" backend frameworks title

### ISSUE THREAD

**Issue by alinkedd** [Devographics/Monorepo#401]
https://2023.stateofjs.com/ua-UA/other-tools/#backend_frameworks or https://2023.stateofjs.com/hu-HU/other-tools/#backend_frameworks leads to UNDEFINED title.

The problem is, I believe, the resolving of double `aliasFor` for the `other_tools.backend_frameworks` key in some languages with updated `state_of_js` file like this:

other_tools.backend_frameworks => tools_others.backend_frameworks => sections.back_end_frameworks.title

![Screenshot from 2024-06-29 02-56-30](https://github.com/Devographics/Monorepo/assets/9061686/d4201d7e-4342-4d54-8da6-9923094aa1a6)

**Comment by alinkedd** [comment]
It may be related to #356

**Comment by brunnerh** [comment]
Still undefined:

![image](https://github.com/user-attachments/assets/66ec0a37-d383-4621-b907-59dc87ff72f8)

**Comment by dimatakoy** [comment]
Yay! It's really undefined. Unbelivable.

**Comment by dimatakoy** [comment]
Still broken
![telegram-cloud-photo-size-2-5418289905093699871-y](https://github.com/user-attachments/assets/a2e75024-aa3b-45e2-8772-f6f0dd4b96d0)
