### ISSUE TITLE
The Logo SVG for State of React 2023 has been set wrong `aria-label` value "State of JS 2021"

### ISSUE THREAD

**Issue by taigakiyokawa** [Devographics/Monorepo#411]
Thank you for summarizing surveys and creating a great website!

I found a bit accessibility problem in that the State of React 2023 logo has wrong label by setting `aria-label="State of JS 2021"`.

You can check the issue by accessing https://2023.stateofreact.com/en-US with DevTools and focusing on the `<svg>` element of the logo.

![image (7)](https://github.com/user-attachments/assets/e1c12347-cef9-4691-ab6b-88beca25166d)

Please check and fix it if you have free time 🙏  (Or, I can do it if you maintainers welcome my PR.)

Thank you.

**Comment by taigakiyokawa** [comment]
I saw there are the same problem in other survey logos:

https://github.com/search?q=repo%3ADevographics%2FMonorepo%20aria-label%3D%22State%20of%20JS%202021%22&type=code

**Comment by SachaG** [comment]
A PR would be great! Thanks for noticing this!

**Comment by eric-burel** [comment]
Thanks! I've tried to fix the issue but the thing is that it stems down from the result app having some copy-pasta around and use a kind of virtual system module, but I couldn't make the types right
This is something that would be solved by some proper upgrade of the results app
