### ISSUE TITLE
can't get to my reading list

### ISSUE THREAD

**Issue by DaveEveritt** [Devographics/Monorepo#420]
went back, checked items for the reading lost (this used to be offered more easily) and updated a couple, but now the survey Qs have gone blank and I can't swipe right to see my existing responses

**Comment by DaveEveritt** [comment]
didn't realise that nothing is saved unless I hit prev/next - was swiping on my iPad

**Comment by SachaG** [comment]
Oh sorry about that… Yeah I guess if you swipe back (or click the back button in your browser) then it won't actually submit the form. Maybe we should add a "you have unsaved data, are you sure you want to leave this page?" warning?

**Comment by DaveEveritt** [comment]
yes, I think a simple warning would be all that's necessary - really appreciate the response :-)On 24 Aug 2024, at 16:37, Sacha Greif ***@***.***> wrote:﻿
Oh sorry about that… Yeah I guess if you swipe back (or click the back button in your browser) then it won't actually submit the form. Maybe we should add a "you have unsaved data, are you sure you want to leave this page?" warning?
