### ISSUE TITLE
Incorrect Copyright Year in Footer

### ISSUE THREAD

**Issue by apicgg** [Devographics/Monorepo#422]
# Incorrect Copyright Year in Footer of [survey.devographics.com](https://survey.devographics.com/en-US)

## Description

The copyright year displayed in the footer of the website [https://survey.devographics.com/en-US](https://survey.devographics.com/en-US) appears to be outdated. Currently, it shows a year that does not match the current calendar year.

## Steps to Reproduce

1. Visit the URL: [https://survey.devographics.com/en-US](https://survey.devographics.com/en-US).
2. Scroll down to the footer section of the page.
3. Observe the copyright year mentioned.

![image](https://github.com/user-attachments/assets/593bdd00-8b9b-4f2a-8010-71e444392e30)

## Expected Result
The copyright year in the footer should reflect the current year (2024).

## Actual Result
The footer displays an incorrect copyright year.

## Suggested Fix
Update the copyright year in the footer to the current year (2024).

**Comment by eric-burel** [comment]
Thanks, will be fixed in next release. This needed a `supressHydrationWarning` to be fully robust to SSR.
