### ISSUE TITLE
"undefined" titles in the State of CSS 2024 Reading List sent by email

### ISSUE THREAD

**Issue by 4esnog** [Devographics/Monorepo#423]
I have just filled the State of CSS 2024 surcey, saving some features to the reading list, and after submitting the survey, chose to send the reading list to my email.

In the email, some of the features' titles are "undefined" instead of the real names.

Here is an example screenshot of how it looks like:

<img width="1016" alt="Screenshot 2024-08-25 at 12 48 34" src="https://github.com/user-attachments/assets/38f8b6f5-4390-466e-8504-eb3680806ef5">

And a text version of all the `undefined`'s I got:

> ### undefined
>
> The CSS data type represents a mathematical function that describes the rate at which a value changes.
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/easing-function
> [Using linear() for better animation](https://fullystacked.net/posts/linear/) ([fullystacked.net](http://fullystacked.net/))
> [Linear() Generator](https://linear-easing-generator.netlify.app/) ([linear-easing-generator.netlify.app](http://linear-easing-generator.netlify.app/))
> 
> ### undefined
> 
> [Using Different Color Spaces for Non-Boring Gradients](https://css-tricks.com/color-spaces-for-more-interesting-css-gradients/) ([css-tricks.com](http://css-tricks.com/))
> 
> ### undefined
> 
> The @layer CSS at-rule is used to declare a cascade layer and can also be used to define the order of precedence in case of multiple cascade layers.
> 
> https://developer.mozilla.org/en-US/docs/Web/CSS/@layer

**Comment by eric-burel** [comment]
@SachaG it measn the entity has no "nameClean", are they expected to always have such a name? or is it ok to do "entity?.nameClean || entity?.name" ?

**Comment by eric-burel** [comment]
I've improved the template generator for these emails, should be ok on develop.
