### ISSUE TITLE
No way to create a reading list

### ISSUE THREAD

**Issue by jonh-polarity** [Devographics/Monorepo#427]
On reviewing my survey results on 9/13/24, I see a message:

> Reading List
> You don't have any items in your reading list. Try going back to the survey and adding features or libraries you'd like to learn more about using the "+" button.

There are no "+" buttons nor any other way to create a reading list in the survey UI. This appears to be a missing or broken feature.

**Comment by SachaG** [comment]
I guess the reading list is disabled for closed surveys since they become read-only. It's not ideal but this way we can be sure the document is not modified once the survey is over.

**Comment by eric-burel** [comment]
Thanks for opening this issue, I am removing the message altogether when the survey is closed + you didn't create a reading list initially (since we don't allow creating a reading lists after the survey is closed)
