### ISSUE TITLE
Everyone is in the top 100%

### ISSUE THREAD

**Issue by chasm** [Devographics/Monorepo#428]
Have seen this in multiple surveys (HTML and CSS). After scoring, the message says, "You have scored in the top 100%" (or similar).

Hello! EVERYBODY WHO TAKES THE SURVEY SCORES IN THE TOP 100%. Math not your strong point? Did you mean top 10% or top 1%?

Funny mistake, but maybe fix it?

**Comment by SachaG** [comment]
1. Since this is a comparative score I think it's normal that everybody defaults to being in the top 100% in the beginning. 
2. The amount of how much I care about this issue is also in the top 100%, technically.

**Comment by eric-burel** [comment]
It's already fixed in the "dev" version, will be fixed for next release

I've actually written my latest article on this topic, you can read more about how we implemented this feature:
https://www.ericburel.tech/blog/vercel-crons
