### ISSUE TITLE
`warning: the following paths have collided` during `git clone`

### ISSUE THREAD

**Issue by alinkedd** [Devographics/Monorepo#432]
```zsh
➜  git clone git@github.com:Devographics/Monorepo.git

...

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'results/src/core/components/NewsletterPOST.tsx'
  'results/src/core/components/NewsletterPost.tsx'
```
I suppose, there should be only one of the following files:
- https://github.com/Devographics/Monorepo/blob/main/results/src/core/components/NewsletterPOST.tsx
- https://github.com/Devographics/Monorepo/blob/main/results/src/core/components/NewsletterPost.tsx

**Comment by eric-burel** [comment]
Thanks for noticing, this will be fixed on next merge on main branch (probably tomoroow)
