### ISSUE TITLE
Unable to submit Survey Signup form

### ISSUE THREAD

**Issue by alexrnmg** [Devographics/Monorepo#443]
I'm unable to sign up in the Survey Signup form on the Conclusion page. 

Url: https://2024.stateofcss.com/en-US/conclusion/

error message in JS console:
Uncaught (in promise) SyntaxError: Unexpected end of JSON input
    at handleSubmit (Newsletter.tsx:39:39)
    
Tested in Chrome v130 & Safari 17.1.2
on an M1 Macbook pro running Mac OS Sonoma 14.1.2
 

<img width="1128" alt="Screenshot 2024-10-29 at 10 12 49 AM" src="https://github.com/user-attachments/assets/7ad864a8-2e6d-49f1-b06d-dbf00d356fda">

**Comment by SachaG** [comment]
Should be fixed once the site redeploys.
