### ISSUE TITLE
TextList component does not work with longText: true option

### ISSUE THREAD

**Issue by SachaG** [Devographics/Monorepo#446]
<img width="754" alt="Screenshot 2024-11-06 at 11 08 31" src="https://github.com/user-attachments/assets/1b9183a3-9031-4795-b573-7ac94061cb29">

In the State of HTML 2024 survey the `html_pain_points_freeform` question had `template: textList` with `longText: true`, which causes the contents of the field to be cleared out as soon as the input loses focus.

**Comment by eric-burel** [comment]
Yep it was dismissing updates coming from a textarea and only supported text inputs, now fixed
