### ISSUE TITLE
Line charts seem unresponsive

### ISSUE THREAD

**Issue by brunnerh** [Devographics/Monorepo#471]
Resized the window, making it smaller [here](https://2024.stateofjs.com/en-US/libraries/mobile_desktop/):

![image](https://github.com/user-attachments/assets/5fa8943d-db23-4ec4-99fc-5a7b1da13bd6)

Reloaded page with small viewport & made it larger again:

![image](https://github.com/user-attachments/assets/12822d0a-0f1f-4b64-86bc-0a97e30a68b1)

(Chrome 131 & Firefox 133.0.3, Windows 10)

**Comment by SachaG** [comment]
Don't resize the window :)
