### ISSUE TITLE
"Native Apps" needs a tooltip and possibly a better label

### ISSUE THREAD

**Issue by brunnerh** [Devographics/Monorepo#472]
There is *no way* that awareness of what a *native application* is, fluctuates like this:

![image](https://github.com/user-attachments/assets/db26f6b7-704c-4024-8942-cc4c7fa48aab)

The way it is written, a lot of people are probably thinking "is that like NativeScript? never heard of it".

There should be some explanation in the survey to make it clear what is being meant and the spelling/capitalization probably should not make it look like some unified product either.

**Comment by SachaG** [comment]
Good point, adding that to suggestions for 2025.
