### ISSUE TITLE
State Of Js 2024 - Gentleman Programming Content Creator Data Missing

### ISSUE THREAD

**Issue by Alan-TheGentleman** [Devographics/Monorepo#478]
Hi ! I'm Gentleman Programming, I appear on the rankings as the top 3 creator for Spanish Language !

But I think there's data missing, only YouTube appears and I don't have a profile picture :(

Here's all my data !

https://doras.to/gentleman-programming

![image](https://github.com/user-attachments/assets/8d21abbf-e770-40f8-9e5f-9587d47ce072)

**Comment by Alan-TheGentleman** [comment]
Let me leave a pair of images !
![Mustachy_Squared](https://github.com/user-attachments/assets/10a5fb2b-2853-46a7-83a1-3635e13a98bc)
![Mustachy](https://github.com/user-attachments/assets/278d45da-077d-40ae-8481-7ba0b8471d62)

**Comment by SachaG** [comment]
Thanks, I'll add the image.
