### ISSUE TITLE
The "CanIUse" link for CSS Containment is incorrect

### ISSUE THREAD

**Issue by mvonballmo** [Devographics/Monorepo#58]
### How to Reproduce

- Browse to https://2021.stateofcss.com/en-US/features/other-features#containment
- Click the "CanIUse" link in this section

### Observed

The link points to `https://caniuse.com/undefined`

### Expected

The link points to `https://caniuse.com/css-containment`

**Comment by eric-burel** [comment]
Thanks, it now points to Mozilla directly
