### ISSUE TITLE
The permalinks next to the headers lack a #

### ISSUE THREAD

**Issue by mvonballmo** [Devographics/Monorepo#59]
### Steps to reproduce

- Browse to https://2021.stateofcss.com/en-US/features/other-features
- Click the chain-link that appears on hover next to the "CSS Variables (Custom Properties)" title
- 404

### Observed

Clicking on any of the chain-links next to a title results in a 404.

### Expected

Clicking on any of the chain-links next to a title should jump to the permalink for that section.

### Analysis

The generated link does not include a # in front of the anchor.

**Comment by eric-burel** [comment]
Sounds ok in current version (it's a tad more complicated because this link is also used for screenshot generation)
