### ISSUE TITLE
Chart Sponsoring Feature

### ISSUE THREAD

**Issue by SachaG** [Devographics/Monorepo#69]
Leave your feedback or ask your questions regarding the chart sponsoring/donations feature here.

**Comment by NessDan** [comment]
It doesn't work 😢 

![image](https://user-images.githubusercontent.com/304269/154518147-bf5353b3-029f-4140-8bda-dde92524b42f.png)
![image](https://user-images.githubusercontent.com/304269/154518170-65bc7961-b40a-41b9-80a9-0409d92f52aa.png)

The URL in question: https://transactions.sendowl.com/products/78664028/05ECB2ED/add_to_cart

**Comment by sambunting** [comment]
I don't think the sponsorship feature is working? I sponsored a chart this morning and this evening my Twitter avatar still isn't there?

Might just be me, but I've also checked a number of other charts and I still can't see any that are sponsored. Am I missing something?

**Comment by sambunting** [comment]
I've just checked again - I'm there! It looks like it's working. At least for me anyway.

**Comment by SachaG** [comment]
> It doesn't work 😢
> The URL in question: https://transactions.sendowl.com/products/78664028/05ECB2ED/add_to_cart

Yeah this happens when the system think a chart is already in someone's cart. Since there's only 1 inventory item for each chart it doesn't let you buy it. I've reported the bug to SendOwl. 

> I've just checked again - I'm there! It looks like it's working. At least for me anyway.

I haven't set up an automated deploy hook yet so I had to manually rebuild, sorry for the delay! And thanks for sponsoring :)

**Comment by cajotafer** [comment]
> I haven't set up an automated deploy hook yet so I had to manually rebuild, sorry for the delay! And thanks for sponsoring :)

This is what I was looking for. Just sponsored a chart a few hours ago :D

**Comment by SachaG** [comment]
Sorry I still have to manually redeploy, I'll do it now.

**Comment by gokulkrishh** [comment]
@SachaG No issues, I see my twitter avatar. Thanks.
