### ISSUE TITLE
ReScript and Reason 

### ISSUE THREAD

**Issue by vmarcosp** [Devographics/Monorepo#77]
Why Reason is listed as a JavaScript Flavor? Reason is not a JavaScript flavor anymore, it's just a syntax for OCaml that used to be the default option to write JavaScript applications with BuckleScript (a tool that compiles OCaml to JavaScript).
Since BuckleScript was rebranded to ReScript and created its language I think the answers corresponding to "Reason" should be considered as ReScript, because Reason now is focused on the native side and all developers that are using "Reason" to write JavaScript applications are using ReScript. What do you think?

**Comment by eric-burel** [comment]
Will close as outdated @SachaG
