### ISSUE TITLE
About: Project Funding section folded into Representativeness & Inclusivity section

### ISSUE THREAD

**Issue by myakura** [Devographics/Monorepo#85]
![Screenshot: Representativeness & Inclusivity section in the JS 2021 survey page](https://user-images.githubusercontent.com/413984/156912428-cc240626-85d4-4748-9fb3-6978ad6cc2da.png)

This occurs both in JS 2021 and CSS 2021 surveys.

https://2021.stateofjs.com/en-US/about#project-funding
https://2021.stateofcss.com/en-US/about#project-funding

The data is coming from Markdown inside YAML files, but to me they look fine...

https://github.com/StateOfJS/locale-en-US/blob/fd2eeeaef7f36c2eafe4324df290d7215d1a4101/state_of_js_2021_results.yml#L392-L409

**Comment by SachaG** [comment]
I think it's missing an extra line break after the `ul`, I don't know why it's needed…
