### ISSUE TITLE
Do not use "circle size" visualizations to convey proportion

### ISSUE THREAD

**Issue by LeaVerou** [Devographics/Monorepo#96]
From [the State of CSS 2021 results](https://2020.stateofcss.com/en-US/features/):

<img width="776" alt="image" src="https://user-images.githubusercontent.com/175836/175285409-9898d27b-f7dc-45fd-b564-97e466144f95.png">

This kind of thing is actually [a big antipattern in dataviz](http://www.perceptualedge.com/articles/08-21-07.pdf). First any data visualization that requires humans to compare areas is already at a disadvantage because humans are pretty bad at comparing areas. But the "circle size" visualization is especially problematic:

- People are usually [confused if they need to compare radius or area](https://www.quora.com/Data-Visualization-When-news-articles-use-circle-size-to-represent-something-do-they-usually-mean-area-or-radius)
- Radius is a poor way to show relationships: a circle with half the radius is π(r/2)² = πr²/4 = a quarter of the area. 

A quick demonstration:
<img width="769" alt="image" src="https://user-images.githubusercontent.com/175836/175286774-a6f687cc-3d37-488a-bc66-f58ca6730404.png">

Is your intuition about these relationships the same as the numbers displayed?

I would suggest using pie charts instead. The argument about areas still applies, but I think pie charts are fine for communicating a proportion of one variable, they start breaking down when you need to show multiple slices. And they do not suffer from the mismatched percentage shown and proportion of area that "circle size" visualizations have.

**Comment by eric-burel** [comment]
Taking the point here about radius vs area interpretation, that's true. However I feel like the chart serves more as a relative comparison and rough approximation of adoption rather than displaying a precise value. I am closing in order to reduce the amount of open issues we have but @SachaG please take a look at it if you happen to work on the results app.
